import Head from "next/head";

import { Inter } from "@next/font/google";
const inter = Inter({ subsets: ["latin"] });

import ProjectCard from "@/components/ProjectCard";
import { projects } from "@/utils/constants";

export default function Home() {
  return (
    <>
      <Head>
        <title>Aniket Kasale | Projects</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="text-gray-800 bg-slate-700 m-0 p-10">
        <h1 className="text-center text-gray-50 text-5xl md:text-6xl font-semibold">
          Projects
        </h1>
        <div className="mt-10">
          {projects.map((item, index) => {
            return <ProjectCard project={item} index={index} />;
          })}
        </div>
      </main>
    </>
  );
}
