export const projects = [
  {
    id: "1",
    img: "/assets/yt.png",
    title: "Video Streaming App - YouTube Clone",
    summery: [
      "This is a clone of the popular video-sharing platform YouTube, developed as a part of Akshay Saini's Namaste React course. It is built using modern front-end technologies, including React, Redux Toolkit, TailwindCSS, and other libraries.",
    ],
    tech: "React, Redux, Tailwind, Shimmer UI",
    gitHub: "https://github.com/aniketkasale/yt-clone",
    demo: "https://youtube-byak.netlify.app",
  },
  {
    id: "2",
    img: "/assets/quizapp.png",
    title: "Time-Bound Quiz App",
    summery: [
      "A web application built using ReactJS that allows users to take a quiz within a specified time frame. The quiz questions are displayed one at a time, and the user must select an answer within a given time limit. The app will automatically move on to the result page once the time limit is reached.",
    ],
    tech: "React, Redux, React Router",
    gitHub: "https://github.com/aniketkasale/Time-Bound-Quiz-App",
    demo: "https://quiz-app-byak.netlify.app/",
  },
  {
    id: "3",
    img: "/assets/quickbite.png",
    title: "Food ordering App - Quick bite",
    summery: [
      "The food ordering app project utilized Swiggy data for practice purposes and implemented dynamic routing, custom hooks, and code splitting using Parcel.js for optimal performance. Shimmer UI was utilized for real-time updates via APIs and asynchronous requests. The project helped expand knowledge in web development and provided valuable experience in building a user-friendly and practical application.",
    ],
    tech: "React, Redux, Tailwind",
    gitHub: "https://github.com/aniketkasale/quick-bite",
    demo: "https://quickbiteapp.netlify.app/",
  },
  {
    id: "4",
    img: "/assets/gkeep.png",
    title: "Google Keep Clone",
    summery: [
      "Google Keep clone! Users can create, delete, and archive notes, with tabs to view deleted and archived notes. The app also has a sorting and filtering feature to easily find notes based on creation time, reminder time, and more. Simplify your note-taking process with this handy tool!",
    ],
    tech: "React, Tailwind",
    gitHub: "https://github.com/aniketkasale/google-keep-clone",
    demo: "https://google-keep-by-aniket.netlify.app/",
  },
  {
    id: "5",
    img: "/assets/todo.png",
    title: "Todo App",
    summery: [
      "This is a simple todo app built with React, which allows you to add, delete, and mark tasks as complete. You can also filter active and completed tasks, store tasks in local storage, and switch between light and dark theme.",
    ],
    tech: "React",
    gitHub: "https://github.com/aniketkasale/todo-app",
    demo: "https://todo-app-byak.netlify.app/",
  },
  {
    id: "6",
    img: "/assets/umbrella.png",
    title: "Customize Umbrella",
    summery: [
      "A umbrella customizer tool that allows users to choose from multiple colors of the umbrella and add their own logo to it. It's perfect for corporate brands who want to add their branding to their merchandise.",
    ],
    tech: "HTML, CSS, JavaScript",
    gitHub: "https://github.com/aniketkasale/customize-umbrella",
    demo: "https://customize-umbrella-ak.netlify.app/",
  },
  {
    id: "7",
    img: "/assets/counter.png",
    title: "Counter App",
    summery: [
      "A simple counter app built with React that has a reset button, a custom value feature to increment/decrement, and a color-changing feature based on the counter's value (green for positive and red for negative).",
    ],
    tech: "HTML, CSS, JavaScript, React",
    gitHub: "https://codesandbox.io/s/counter-app-dgpt7z",
    demo: "https://dgpt7z.csb.app/",
  },
  {
    id: "8",
    img: "/assets/goodfood.png",
    title: "Good Food",
    summery: [
      "A simple app which shows options for healthy meal and breakfast",
    ],
    tech: "HTML, CSS, JavaScript, React",
    gitHub: "https://codesandbox.io/s/goodfood-x6wts?file=/src/App.js",
    demo: "https://x6wts.codesandbox.io/",
  },
  {
    id: "9",
    img: "/assets/stocks.png",
    title: "Stocks Calculator",
    summery: [
      "The Stocks Calculator is a tool that helps you easily calculate your potential profits and losses in the stock market. With just a few clicks, you can determine the current value of your stocks, calculate the percentage gain or loss from your initial investment, and evaluate the potential profit or loss on a future sale. ",
    ],
    tech: "HTML, CSS, JavaScript",
    gitHub: "https://github.com/aniketkasale/stocksCalc",
    demo: "https://stockscalc.netlify.app/",
  },
  {
    id: "10",
    img: "/assets/funtriangle.png",
    title: "Fun With Triangles",
    summery: [
      "In this app there are multiple features (i) you can provide angles and check are they forming triangle or not, (ii) Quiz, (iii) Calculate hypotenuse, (iv) Calculate Area",
    ],
    tech: "HTML, CSS, JavaScript",
    gitHub: "https://funtrianglesaniket.netlify.app/",
    demo: "https://funtrianglesaniket.netlify.app/index.html",
  },
  {
    id: "11",
    img: "/assets/minions.png",
    title: "Minion Speak",
    summery: ["A simple app which traslates english to minions language"],
    tech: "HTML, CSS, JavaScript, API",
    gitHub: "https://github.com/aniketkasale/Minion_Speak",
    demo: "https://miniontranslate1.netlify.app/",
  },
  {
    id: "12",
    img: "/assets/shakespear.png",
    title: "Shakespear Speak",
    summery: ["A simple app which traslates english to shakespear language"],
    tech: "HTML, CSS, JavaScript, API",
    gitHub: "https://github.com/aniketkasale/Shakespear_Speak",
    demo: "https://shakespearspeak.netlify.app/",
  },
  {
    id: "13",
    img: "/assets/knowEmo.png",
    title: "Know Your Emotions",
    summery: ["A simple app which shows name of emoji you entered"],
    tech: "HTML, CSS, JavaScript, React",
    gitHub: "https://codesandbox.io/s/confident-dewdney-f4006?file=/src/App.js",
    demo: "https://f4006.codesandbox.io/",
  },

  {
    id: "14",
    img: "/assets/cashregister.png",
    title: "Cash Register    ",
    summery: [
      "The Cash Register App simplifies cash transactions by quickly calculating the correct change due to customers. ",
    ],
    tech: "HTML, CSS, JavaScript",
    gitHub: "https://github.com/aniketkasale/Cash_Register",
    demo: "https://cashregisteraniket.netlify.app/",
  },
  {
    id: "15",
    img: "/assets/birthdaypalindrome.png",
    title: "Check Your Birthday is Palindrome or not?",
    summery: [
      "A simple app where you can check your birthday is palindrome or not.",
    ],
    tech: "HTML, CSS, JavaScript",
    gitHub: "https://github.com/aniketkasale/CheckbirthdayPalindrome",
    demo: "https://checkbirthdaypalindrome.netlify.app/",
  },
  {
    id: "16",
    img: "/assets/luckyBirthDay.png",
    title: "Is Your Birthday Lucky?    ",
    summery: [
      "A simple app where you can check your birthday is lucky or not.",
    ],
    tech: "HTML, CSS, JavaScript",
    gitHub: "https://github.com/aniketkasale/BirthdayLucky",
    demo: "https://ismybirthdaylucky.netlify.app/",
  },
  {
    id: "17",
    img: "/assets/flash.png",
    title: "Flash Quiz",
    summery: ["A CLI app where you can play quiz about flash."],
    tech: "Vanilla JavaScript",
    gitHub: "https://github.com/aniketkasale/Flash-Quiz",
    demo: "https://replit.com/@aniketkasale02/Flash#index.js?embed=1&output=1",
  },
  {
    id: "18",
    img: "/assets/institute.png",
    title: "Institute Website",
    summery: ["A institute website which is developed in pure HTML, CSS"],
    tech: "HTML CSS",
    gitHub: "https://github.com/aniketkasale/InstituteSiteTemplate",
    demo: "https://institute-web.netlify.app/",
  },
];
